# NumPy Introduction

* NumPy stands for Numerical Python and also known as array oriented computing.
* NumPy is a library written for scientific computing and data analysis.
* NumPy consists of a powerful data structure called multidimensional arrays.
* The most basic object in Numpy is the ndarray, or simply an array which is an n-dimensional, homogeneous array. By homogenous, we mean that all the elements in a NumPy array have to be of the same data type, which is commonly numeric (float or integer).

# Why NumPy?
* convenience & speed
* NumPy is much faster than the standard python ways to do computations.
* We don't have to do the explicit looping and indexing etc. (all of this happens behind the scenes, in precompiled C-code), and thus it is much more concise.
* NumPy arrays are more compact than lists, i.e. they take much lesser storage space than lists

# Installation of NumPy

In [ ]:
!pip install numpy

# Importing numpy library

In [2]:
import numpy as np

# creating array using .array() method

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

# 0-D Arrays
0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [ ]:
arr = np.array(42)

print(arr)

# 1-D Arrays
An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

These are the most common and basic arrays.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

# 2-D Arrays
An array that has 1-D arrays as its elements is called a 2-D array.

These are often used to represent matrix or 2nd order tensors.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

# Check type , dimensions  , shape , size , type

In [ ]:
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )

In [ ]:
# Printing type of arr object
print("Array is of type: ", type(arr))

In [ ]:
# Printing array dimensions (axes)
print("No. of dimensions: ", arr.ndim)

In [ ]:
# Printing shape of array
print("Shape of array: ", arr.shape)
 

In [ ]:
# Printing size (total number of elements) of array
print("Size of array: ", arr.size)

In [ ]:
# Printing type of elements in array
print("Array stores elements of type: ", arr.dtype)

# Functions for creating array

In [ ]:
arr = np.ones((3, 3))

print(arr)

print(arr.dtype)

print(arr.itemsize)

In [ ]:
arr = np.zeros((3, 3))

print(arr)

In [ ]:
arr = np.eye(3)

print(arr)

In [ ]:
arr = np.arange(5)

print(arr)

In [ ]:
arr = np.arange(1, 10)

print(arr)

In [ ]:
arr = np.arange(1, 10, 2)

print(arr)

# Numpy Random Numbers

1) np.random.rand - generates an array with random numbers that are uniformly distribute between 0 and 1.

2) np.random.randn - generates an array with random numbers that are normally distributed, mean = 0 and stdev = 1.

3) np.random.randint - generates an array with random numbers (integers) that are uniformly distribute between 0 and given number.

4) np.random.uniform - generates an array with random numbers (float) between given numbers.

In [ ]:
# np.random.rand - generates an array with random numbers that are uniformly distribute between 0 and 1.

arr = np.random.rand(5)

print(arr)

In [ ]:
print(np.random.rand(10,2))

In [ ]:
# np.random.randn - generates an array with random numbers that are normally distributed, mean = 0 and stdev = 1.

print(np.random.randn(5))

In [ ]:
print(np.random.randn(5, 4))

In [ ]:
# np.random.randint - generates an array with random numbers (integers) that are uniformly distribute between 0 and given number.

print(np.random.randint(35, 40, size = (5, 4)))

In [ ]:
#  np.random.uniform - generates an array with random numbers (float) between given numbers.

print(np.random.uniform(5, size = (5, 4)))

In [ ]:
print(np.random.uniform(35, 40, size = (5, 4)))

# Numpy Indexing

In [ ]:
arr = 2 * np.arange(10)

print(arr)

print(arr[3])

In [ ]:
# accessing first element
arr[0]

In [ ]:
# accessing last element
arr[-1]

In [ ]:
# accessing multiple elements
arr[[0,2,4]]

In [ ]:
print(arr[15])


In [ ]:
# matrix
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr[1, 2])

In [ ]:
# update items in matrix
arr[1, 2] = 99

print(arr)

In [ ]:
arr1 = np.array([[1, 2, 3], [4, 5, 6], [8, 77, 85]])

print(arr1[2, 2])

# Numpy Slicing

In [ ]:
arr2 = np.arange(10)
arr2

In [ ]:
# to get all the elements from 2nd index
arr2[2:]

In [ ]:
# to get all the elements 
arr2[:]

In [ ]:
# to get all the elements from 7nd index
arr2[7:]

In [ ]:
# to get all the elements betweeb 2nd and 7nd index
arr2[2:7]

In [ ]:
# to get all the elements from -6th index
arr2[:-6]

In [ ]:
# to get all the elements from 1st and -6th index
arr2[1:-6]

### n-dimension array slicing

<img src="numpyslice2.png" style="width:20px;heigth:20px"/>

![](numpyslice1.png)

In [ ]:
# consider we have 2D array
a = np.array([[ 0,  1,  2,  3],[ 4,  5,  6,  7],[ 8,  9, 10, 11],[12, 13, 14, 15]])

In [ ]:
a

In [ ]:
# to access 9
# a[rowIndex,columnIndex]

a[2,1]

In [ ]:
# to access 13
a[3,1]

In [ ]:
# to get 5,6,7
#        9,10,11
a[1:3, 1:] 

In [ ]:
# to get 0,1,4,5
a[0:2, 2:3] 

In [ ]:
# to get 0,1,4,5
a[0:2, 2:3] 

In [ ]:
# to get 10,11,14,15
a[2:,2:]

In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr



In [ ]:
#From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
print(arr[0:, 1:])

# Numpy Maths

In [3]:
# ELEMENT WISE OPERATIONS

x = np.array([[1,2], [3,4]])

y = np.array([[5,6], [7,8]])

In [4]:
#add
print(np.add(x, y))


[[ 6  8]
 [10 12]]


In [5]:
#subtract
print(np.subtract(x, y))

[[-4 -4]
 [-4 -4]]


In [6]:
#multiply
print(np.multiply(x, y))

[[ 5 12]
 [21 32]]


In [7]:
#divide
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [8]:
# Matrix Multiplication

print(np.matmul(x, y))

print(np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [9]:
x = np.array([[1,2], [3,4]])

print(np.sum(x))

print(np.sum(x, axis=0)) # Column Wise

print(np.sum(x, axis=1)) # Row wise

10
[4 6]
[3 7]


In [10]:
#minimum
print(np.min(x))

#maximum
print(np.max(x))

1
4


In [11]:
print(x)


[[1 2]
 [3 4]]


In [12]:
# transpose
print(x.T)

[[1 3]
 [2 4]]


# Numpy Statistics

In [15]:
x = np.array([160, 180, 146, 162, 184, 180])

In [16]:
print(np.max(x))

print(np.min(x))

184
146


In [17]:
#mean
print(np. mean(x))

168.66666666666666


In [18]:
#median
print(np.median(x))

171.0


In [19]:
#variance
print(np.var(x))

187.55555555555557


In [20]:
#standard deviation
print(np.std(x))

13.695092389449425


# Numpy Reshape

In [ ]:
import numpy as np

In [21]:
arr = np.arange(0, 50, 5)

print(arr)

[ 0  5 10 15 20 25 30 35 40 45]


In [22]:
#reshape
arr2d = arr.reshape(2, 5)

print(arr2d)

[[ 0  5 10 15 20]
 [25 30 35 40 45]]


In [23]:
arr2d = arr.reshape(5, 2)

print(arr2d)

[[ 0  5]
 [10 15]
 [20 25]
 [30 35]
 [40 45]]


In [24]:
arr2d = arr.reshape(3, 3)

ValueError: cannot reshape array of size 10 into shape (3,3)

In [25]:
arr = np.arange(5, 50)

print(arr.shape)

(45,)


In [26]:
print(arr.reshape(5, 9))

[[ 5  6  7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20 21 22]
 [23 24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49]]


In [27]:
print(arr.reshape(3, 3, 5))

[[[ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]]

 [[35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]]


In [28]:
#flatten
print(arr.flatten())

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28
 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# Miscellaneous Topics

### Linspace

In [29]:
# Syntax => np.linspace(begin, end, # of elements)

print(np.linspace(1, 5, 9))

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


In [30]:
print(np.linspace(10,13,6))

[10.  10.6 11.2 11.8 12.4 13. ]


### Sorting

In [31]:
arr = np.random.randint(50, 100, size = (5, 10))

print(arr)

[[52 93 69 84 58 67 68 77 78 98]
 [66 96 98 65 81 71 67 79 98 73]
 [60 89 67 80 80 51 79 52 99 83]
 [58 76 91 86 58 79 99 66 64 97]
 [79 79 61 54 77 68 97 90 67 55]]


In [32]:
# Column Wise Sorting

np.sort(arr, axis = 0)

array([[52, 76, 61, 54, 58, 51, 67, 52, 64, 55],
       [58, 79, 67, 65, 58, 67, 68, 66, 67, 73],
       [60, 89, 69, 80, 77, 68, 79, 77, 78, 83],
       [66, 93, 91, 84, 80, 71, 97, 79, 98, 97],
       [79, 96, 98, 86, 81, 79, 99, 90, 99, 98]])

In [33]:
# Row Wise Sorting

np.sort(arr, axis = 1)

array([[52, 58, 67, 68, 69, 77, 78, 84, 93, 98],
       [65, 66, 67, 71, 73, 79, 81, 96, 98, 98],
       [51, 52, 60, 67, 79, 80, 80, 83, 89, 99],
       [58, 58, 64, 66, 76, 79, 86, 91, 97, 99],
       [54, 55, 61, 67, 68, 77, 79, 79, 90, 97]])

### Stacking

In [34]:
arr1 = np.arange(5,15).reshape(2,5)
print(arr1)

[[ 5  6  7  8  9]
 [10 11 12 13 14]]


In [35]:
arr2 = np.arange(25,35).reshape(2,5)
print(arr2)

[[25 26 27 28 29]
 [30 31 32 33 34]]


In [36]:
np.vstack([arr1, arr2])

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [37]:
np.hstack([arr1, arr2])

array([[ 5,  6,  7,  8,  9, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 30, 31, 32, 33, 34]])

### Concatenate

In [38]:
np.concatenate([arr1, arr2], axis = 0) # adding row wise

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [39]:
np.concatenate([arr1, arr2], axis = 1) # adding Column wise

array([[ 5,  6,  7,  8,  9, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 30, 31, 32, 33, 34]])

### Append

In [40]:
np.append(arr1, arr2, axis = 0) # adding row wise

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [41]:
np.append(arr1, arr2, axis = 1) # adding Column wise

array([[ 5,  6,  7,  8,  9, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 30, 31, 32, 33, 34]])

### Where

In [42]:
arr = np.arange(50, 100).reshape(5, 10)

print(arr)

[[50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [43]:
np.where(arr > 64, 0, arr)

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [44]:
np.where(arr > 64, arr/10, arr)

array([[50. , 51. , 52. , 53. , 54. , 55. , 56. , 57. , 58. , 59. ],
       [60. , 61. , 62. , 63. , 64. ,  6.5,  6.6,  6.7,  6.8,  6.9],
       [ 7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,  7.7,  7.8,  7.9],
       [ 8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,  8.8,  8.9],
       [ 9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,  9.9]])